version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: aesh123
      POSTGRES_DB: doctorAppointmentsDb
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis-1
    ports:
      - "6379:6379"

  user-service:
    build: ./services/user-service
    ports:
      - "4001:4001"
    depends_on:
      - postgres
      - redis
    environment:
      PORT: ${USER_SERVICE_PORT}
      DATABASE_URL: ${USER_SERVICE_DATABASE_URL}
      REDIS_URL: ${USER_SERVICE_REDIS_URL}
      JWT_SECRET: ${USER_SERVICE_JWT_SECRET}
      CLOUDINARY_CLOUD_NAME: ${USER_SERVICE_CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${USER_SERVICE_CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${USER_SERVICE_CLOUDINARY_API_SECRET}
    
  mailer-service:
    build: ./services/mailer-service
    container_name: mailer-service
    restart: always
    depends_on:
      - redis
    environment:
      SENDGRID_API_KEY: ${MAILER_SENDGRID_API_KEY}
      FROM_EMAIL: ${MAILER_FROM_EMAIL}
      
volumes:
  pgdata:

