version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: aesh123
      POSTGRES_DB: doctorAppointmentsDb
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis-1
    ports:
      - "6379:6379"

  user-service:
    build: ./services/user-service
    ports:
      - "4001:4001"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./services/user-service/.env
    
  mailer-service:
    build: ./services/mailer-service
    container_name: mailer-service
    restart: always
    depends_on:
      - redis
    env_file:
      - ./services/mailer-service/.env

volumes:
  pgdata:

