name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub (or ACR if you switch later)
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build & push user-service
      - name: Build & push images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:latest ./services/user-service
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest
          
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mailer-service:latest ./services/mailer-service
          docker push ${{ secrets.DOCKER_USERNAME }}/mailer-service:latest

        

      # Deploy to Azure VM via SSH
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            cd /app
            docker compose pull
            docker compose up -d --remove-orphans
